DROP DATABASE IF EXISTS `demoapp`;
CREATE DATABASE IF NOT EXISTS `demoapp` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `demoapp`;

CREATE TABLE book (id INT AUTO_INCREMENT NOT NULL, location_id INT NOT NULL, title LONGTEXT NOT NULL, INDEX IDX_CBE5A33164D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE book ADD CONSTRAINT FK_CBE5A33164D218E FOREIGN KEY (location_id) REFERENCES book (id);
